/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posttest2;

import java.awt.Font;

/**
 *
 * @author Yam Fay
 */
public class Bio_Mahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Bio_Mahasiswa
     */
    public Bio_Mahasiswa() {
        initComponents();
        kotakajaib.setEnabled(false);
        NEGARA.setEnabled(false);
        KOTAKAN.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Kelamin = new javax.swing.ButtonGroup();
        KELKTP = new javax.swing.ButtonGroup();
        KAWINAN = new javax.swing.ButtonGroup();
        Alas = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        KTM = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        kotaknama = new javax.swing.JTextField();
        kotakNIM = new javax.swing.JTextField();
        kotakfak = new javax.swing.JTextField();
        kotakal = new javax.swing.JTextField();
        tgl = new javax.swing.JComboBox<>();
        bln = new javax.swing.JComboBox<>();
        thn = new javax.swing.JComboBox<>();
        jjg = new javax.swing.JComboBox<>();
        ps = new javax.swing.JComboBox<>();
        Daerah = new javax.swing.JComboBox<>();
        laki = new javax.swing.JRadioButton();
        bini = new javax.swing.JRadioButton();
        pencet = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        kotakajaib = new javax.swing.JTextArea();
        KTP = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        NIK = new javax.swing.JTextField();
        NAMA = new javax.swing.JTextField();
        TMLAHIR = new javax.swing.JTextField();
        ALAMAT = new javax.swing.JTextField();
        RTRW = new javax.swing.JTextField();
        KELDESA = new javax.swing.JTextField();
        CAMAT = new javax.swing.JTextField();
        KERJA = new javax.swing.JTextField();
        NEGARA = new javax.swing.JTextField();
        TGL = new javax.swing.JComboBox<>();
        BLN = new javax.swing.JComboBox<>();
        THN = new javax.swing.JComboBox<>();
        AGAMA = new javax.swing.JComboBox<>();
        LAKI = new javax.swing.JRadioButton();
        BINI = new javax.swing.JRadioButton();
        SUDAH = new javax.swing.JRadioButton();
        BELUM = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        KOTAKAN = new javax.swing.JTextArea();
        KLIK = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        KTM.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIODATA MAHASISWA");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NAMA");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIM");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TANGGAL LAHIR");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("JENIS KELAMIN");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("FAKULTAS");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("JENJANG");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PROGRAM STUDI");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ALAMAT");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Daerah Asal");

        tgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        bln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        thn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1996", "1995", "1994", "1993", "1992", "1991", "1990" }));

        jjg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "D2", "D3", "D4", "S1", "S2", "S3", "S Teler", "S campur", "S Serut", "S Lilin" }));

        ps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Teknik Informatika", "Teknik Komputer", "Sistem Informasi", "Ilmu komputer", " " }));

        Daerah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kab/kota", "Balikpapan", "Bontang", "Sangata", "Tarakan", "Kutai Barat", "Kutai Timur", "Kutai Kartanegara", "Samarinda", "Berau", "Nunukan", "Dunia lain", "Luar Angkasa", "Mars", "Jupiter", "Merkurius", "Saturnus", "urAnus", "Misterius", "Ujung Kulon", "Ujung Pandang", "Ujung Bumi", "INILAH UJUNGNYA" }));

        Kelamin.add(laki);
        laki.setText("LAKI-LAKI");

        Kelamin.add(bini);
        bini.setText("PEREMPUAN");
        bini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biniActionPerformed(evt);
            }
        });

        pencet.setText("MUNCULKAN");
        pencet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencetActionPerformed(evt);
            }
        });

        kotakajaib.setColumns(20);
        kotakajaib.setRows(5);
        jScrollPane1.setViewportView(kotakajaib);

        javax.swing.GroupLayout KTMLayout = new javax.swing.GroupLayout(KTM);
        KTM.setLayout(KTMLayout);
        KTMLayout.setHorizontalGroup(
            KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTMLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(34, 34, 34)
                .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jjg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kotakal, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kotakfak, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kotakNIM, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kotaknama, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KTMLayout.createSequentialGroup()
                            .addComponent(laki)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bini))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, KTMLayout.createSequentialGroup()
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Daerah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pencet)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        KTMLayout.setVerticalGroup(
            KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KTMLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTMLayout.createSequentialGroup()
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kotaknama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(kotakNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(thn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(laki)
                            .addComponent(bini))
                        .addGap(18, 18, 18)
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(kotakfak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jjg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(ps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(kotakal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(KTMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(Daerah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KTMLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pencet)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jPanel1.add(KTM, "card2");

        KTP.setBackground(new java.awt.Color(0, 153, 0));

        jLabel11.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("KARTU TANDA PENDUDUK");

        jLabel12.setText("NIK");

        jLabel13.setText("Nama");

        jLabel14.setText("Tempat lahir");

        jLabel15.setText("Tanggal Lahir");

        jLabel16.setText("Jenis Kelamin");

        jLabel17.setText("Alamat");

        jLabel18.setText("RT / RW");

        jLabel19.setText("Kel / Desa");

        jLabel20.setText("Kecamatan");

        jLabel21.setText("Agama");

        jLabel22.setText("Status Perkawinan");

        jLabel23.setText("Pekerjaan");

        jLabel24.setText("Kewarganegaraan");

        KERJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KERJAActionPerformed(evt);
            }
        });

        NEGARA.setText("WNI");

        TGL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanggal", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        BLN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        THN.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980" }));

        AGAMA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atheis", "Islam", "Kristen", "Katolik", "Hindu", "Konghuchu" }));

        KELKTP.add(LAKI);
        LAKI.setText("LAKI-LAKI");

        KELKTP.add(BINI);
        BINI.setText("PEREMPUAN");

        KAWINAN.add(SUDAH);
        SUDAH.setText("KAWIN");

        KAWINAN.add(BELUM);
        BELUM.setText("BELUM KAWIN");

        KOTAKAN.setColumns(20);
        KOTAKAN.setRows(5);
        jScrollPane2.setViewportView(KOTAKAN);

        KLIK.setText("TAMPILKAN");
        KLIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KLIKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KTPLayout = new javax.swing.GroupLayout(KTP);
        KTP.setLayout(KTPLayout);
        KTPLayout.setHorizontalGroup(
            KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(KTPLayout.createSequentialGroup()
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel20)
                        .addComponent(jLabel19)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)))
                            .addGroup(KTPLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel18))))
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))))
                .addGap(59, 59, 59)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NAMA)
                        .addComponent(TMLAHIR)
                        .addComponent(ALAMAT)
                        .addComponent(RTRW)
                        .addComponent(KELDESA)
                        .addComponent(CAMAT)
                        .addComponent(KERJA)
                        .addComponent(NEGARA, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(NIK))
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addComponent(TGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(THN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(AGAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addComponent(LAKI)
                        .addGap(18, 18, 18)
                        .addComponent(BINI))
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addComponent(SUDAH)
                        .addGap(18, 18, 18)
                        .addComponent(BELUM)))
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                        .addComponent(KLIK, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154))))
        );
        KTPLayout.setVerticalGroup(
            KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KTPLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(NIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TMLAHIR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(TGL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BLN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(THN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(LAKI)
                            .addComponent(BINI))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ALAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(RTRW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(KELDESA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(CAMAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(AGAMA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(SUDAH)
                            .addComponent(BELUM)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KTPLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(KERJA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(KTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(NEGARA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KTPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(KLIK, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel1.add(KTP, "card3");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("KTM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setText("KTP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        javax.swing.GroupLayout AlasLayout = new javax.swing.GroupLayout(Alas);
        Alas.setLayout(AlasLayout);
        AlasLayout.setHorizontalGroup(
            AlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AlasLayout.setVerticalGroup(
            AlasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AlasLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Alas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void biniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biniActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        KTM.setVisible(true);
        KTP.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        KTM.setVisible(false);
        KTP.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pencetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencetActionPerformed
        // TODO add your handling code here:
        
        String JenisKelamin= null;
        if (laki.isSelected())
            JenisKelamin = laki.getText();
        else if (bini.isSelected())
            JenisKelamin = bini.getText();
        String nama = kotaknama.getText();
        String nim = kotakNIM.getText();
        String Fak = kotakfak.getText();
        String al = kotakal.getText();
        
        String TGL = tgl.getSelectedItem().toString();
        String BLN = bln.getSelectedItem().toString();
        String THN = thn.getSelectedItem().toString();
        String JJG = jjg.getSelectedItem().toString();
        String prodi = ps.getSelectedItem().toString();
        String DA = Daerah.getSelectedItem().toString();
        
        kotakajaib.setText("Nama    "+"\t"+":   "+nama
                +"\n"+"\nNIM    "+"\t"+":   "+nim
                +"\n"+"\nTanggal Lahir  "+"\t"+":   "+TGL +"/" +BLN +"/"+THN
                +"\n"+"\nJenis Kelamin  "+"\t"+":   "+JenisKelamin
                +"\n"+"\nFakultas   "+"\t"+":   "+Fak
                +"\n"+"\nJenjang    "+"\t"+":   "+JJG
                +"\n"+"\nProgram Studi  "+"\t"+":   "+prodi
                +"\n"+"\nAlamat "+"\t"+":   "+al
                +"\n"+"\nDaerah Asal    "+"\t"+":   "+DA);
    }//GEN-LAST:event_pencetActionPerformed

    private void KERJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KERJAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KERJAActionPerformed

    private void KLIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KLIKActionPerformed
        // TODO add your handling code here:
        
        String JenisKelamin= null;
        if (LAKI.isSelected())
            JenisKelamin = LAKI.getText();
        else if (BINI.isSelected())
            JenisKelamin = BINI.getText();
        String kawin= null;
        if (SUDAH.isSelected())
            kawin = SUDAH.getText();
        else if (BELUM.isSelected())
            kawin = BELUM.getText();
        
        String nik = NIK.getText();
        String nama = NAMA.getText();
        String tmlhr = TMLAHIR.getText();
        String alamat = ALAMAT.getText();
        String rtrw = RTRW.getText();
        String lurah = KELDESA.getText();
        String camat = CAMAT.getText();
        String kerja = KERJA.getText();
        String negara = NEGARA.getText();
        
        String tgl = TGL.getSelectedItem().toString();
        String bln = BLN.getSelectedItem().toString();
        String thn = THN.getSelectedItem().toString();
        String agama = AGAMA.getSelectedItem().toString();
        
        KOTAKAN.setText("NIK    "+"\t"+":   "+nik
                +"\n"+"\nNama    "+"\t"+":   "+nama
                +"\n"+"\nTempat Lahir    "+"\t"+":   "+tmlhr
                +"\n"+"\nTanggal Lahir  "+"\t"+":   "+tgl +"/" +bln +"/"+thn
                +"\n"+"\nJenis Kelamin  "+"\t"+":   "+JenisKelamin
                +"\n"+"\nAlamat "+"\t"+":   "+alamat
                +"\n"+"\nRT / RW    "+"\t"+":   "+rtrw
                +"\n"+"\nKel / Desa    "+"\t"+":   "+lurah
                +"\n"+"\nKecamatan    "+"\t"+":   "+camat
                +"\n"+"\nAgama   "+"\t"+":   "+agama
                +"\n"+"\nStatus Perkawinan    "+"\t"+":   "+kawin
                +"\n"+"\nPekerjaan  "+"\t"+":   "+kerja
                +"\n"+"\nKewarganegaraan    "+"\t"+":   "+negara);
    }//GEN-LAST:event_KLIKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bio_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bio_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bio_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bio_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bio_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AGAMA;
    private javax.swing.JTextField ALAMAT;
    private javax.swing.JPanel Alas;
    private javax.swing.JRadioButton BELUM;
    private javax.swing.JRadioButton BINI;
    private javax.swing.JComboBox<String> BLN;
    private javax.swing.JTextField CAMAT;
    private javax.swing.JComboBox<String> Daerah;
    private javax.swing.ButtonGroup KAWINAN;
    private javax.swing.JTextField KELDESA;
    private javax.swing.ButtonGroup KELKTP;
    private javax.swing.JTextField KERJA;
    private javax.swing.JButton KLIK;
    private javax.swing.JTextArea KOTAKAN;
    private javax.swing.JPanel KTM;
    private javax.swing.JPanel KTP;
    private javax.swing.ButtonGroup Kelamin;
    private javax.swing.JRadioButton LAKI;
    private javax.swing.JTextField NAMA;
    private javax.swing.JTextField NEGARA;
    private javax.swing.JTextField NIK;
    private javax.swing.JTextField RTRW;
    private javax.swing.JRadioButton SUDAH;
    private javax.swing.JComboBox<String> TGL;
    private javax.swing.JComboBox<String> THN;
    private javax.swing.JTextField TMLAHIR;
    private javax.swing.JRadioButton bini;
    private javax.swing.JComboBox<String> bln;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jjg;
    private javax.swing.JTextField kotakNIM;
    private javax.swing.JTextArea kotakajaib;
    private javax.swing.JTextField kotakal;
    private javax.swing.JTextField kotakfak;
    private javax.swing.JTextField kotaknama;
    private javax.swing.JRadioButton laki;
    private javax.swing.JButton pencet;
    private javax.swing.JComboBox<String> ps;
    private javax.swing.JComboBox<String> tgl;
    private javax.swing.JComboBox<String> thn;
    // End of variables declaration//GEN-END:variables
}
